registerCourse("AAA1_S2", {
  "seriesId": "AAA1",
  "seasonNumber": 2,
  "img": "https://raw.githubusercontent.com/Ahmed-programmer-1/A/main/images/AAA1_S2-1791058720030.webp",
  "name": "اللغة العربية  — الجزء الأول — الموسم 2",
  "description": "اللغة العربية  — الجزء الأول — الموسم 2",
  "exclusive": false,
  "category": "نحو",
  "level": "الموسم 2",
  "categories": [],
  "firstPublishedAt": "2026-10-03T20:18:46.709Z",
  "menuSection": "",
  "singleLang": "ar",
  "seo": {
    "title": "",
    "description": "",
    "h1": "",
    "keywords": "",
    "episodeTitleTemplate": "",
    "episodeDescTemplate": ""
  },
  "info": {
    "overview": "",
    "studio": "",
    "originalLanguage": "",
    "dubLanguage": "",
    "creator": "",
    "startDate": "",
    "endDate": "",
    "writer": "",
    "levelsCount": "",
    "episodesThisLevel": "",
    "status": "",
    "country": "",
    "ageRange": "",
    "releaseDate": [],
    "grade": ""
  },
  "videos": []
});
